# Generated by Django 5.1.4 on 2024-12-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_category_options_alter_product_options_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'updated_at'], 'verbose_name_plural': 'orders'},
        ),
    ]
