# Generated by Django 5.1.4 on 2024-12-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_cart_total_order_email_order_name_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
