# Generated by Django 5.1.4 on 2025-01-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
