# Generated by Django 5.1.4 on 2025-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='agreement_accepted',
        ),
    ]
